#!/bin/sh


basedir=$(cd `dirname $0`; pwd)
parentdir=$(cd $basedir; cd ..; pwd)
hostname=$(hostname)

mkdir -p /var/lib/filebeat/data
chmod -R 777 /var/lib/filebeat/data

mkdir -p /var/lib/docker/containers
chmod -R 777 /var/lib/docker/containers

docker run --name filebeat \
    --log-opt max-size=1g \
    --network=host \
    --restart=always \
    -d \
    --user=root \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /var/lib/filebeat/data:/usr/share/filebeat/data \
    -v /var/lib/docker/containers:/var/lib/docker/containers \
    -v /var/log:/var/log \
    -v $basedir/filebeat.yml:/usr/share/filebeat/filebeat.yml \
    -v $parentdir/hosts:/etc/hosts \
    docker.elastic.co/beats/filebeat:7.9.0
