#!/bin/bash

if [ ! -d "$1" ];then
    echo "第一个参数需要指定应用所在目录"
    exit 1
fi

APP_NAME=$1
stop_timeout=30
start_timeout=30

mkdir -p /var/log/$APP_NAME
chmod -R 777 /var/log/$APP_NAME

cd $APP_NAME

if [ -f "app.pid" ];then
    pid=`cat app.pid`
    kill $pid

    tick=1
    while [ -f "app.pid"  ];do
        if [ $tick -gt $stop_timeout ];then
            echo "\n应用停止($pid)超时: timeout=$stop_timeout"
            exit 1
        fi

        echo -ne "正等待应用($pid)停止: $tick \r"
        sleep 1
        ((tick+=1))
    done

    echo ""
fi

(java -jar app.jar --spring.config.location=classpath:/,file:./ --spring.profiles.active=production >> /var/log/$APP_NAME/app.log 2>&1 &)

tick=1
while [ ! -f "app.pid"  ];do
    if [ $tick -gt $start_timeout ];then
        echo "\n应用启动超时: tick=$tick, timeout=$start_timeout"
        exit 1
    fi

    echo -ne "正等待应用启动: $tick \r"
    sleep 1
    ((tick+=1))
done

echo -n ""
echo "启动完成: pid=`cat app.pid`, cost=$tick"
